"""added username third time

Revision ID: 020223d9aa64
Revises: 91e1f1597419
Create Date: 2022-08-18 14:42:16.637647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020223d9aa64'
down_revision = '91e1f1597419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'username')
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
